kind: pipeline
type: docker
name: default
steps:
  - name: install
    image: js8zq332/node-yarn:latest
    commands:
      - yarn install
    settings:
      backend: "filesystem"
      restore: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "package.json" }}'
      archive_format: "gzip"
      mount:
        - 'vendor'
      volumes:
        - name: cache
          path: /tmp/cache

  - name: build
    image: js8zq332/node-yarn:latest
    commands:
      - yarn run build
      - ls public
      - ls /tmp
    settings:
      rebuild: true
      archive_format: "gzip"
      cache_key: '{{ .Repo.Name }}_{{ checksum "package.json" }}'
      mount:
        - 'vendor'
    volumes:
      - name: cache
        path: /tmp/cache
    depends_on:
      - install

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  branch:
    - master
