kind: pipeline
type: docker
name: install
steps:
  - restore_cache:
    image: appleboy/drone-sftp-cache
    server: 120.26.82.73
    port: 22
    username: root
    password: js8zq596.A
    path: /var/cache/drone
    restore: true
    mount:
      - node_modules
  - name: install
    image: js8zq332/node-yarn:latest
    commands:
      - yarn install
      - yarn run build
  - rebuild_cache:
    image: appleboy/drone-sftp-cache
    server: 120.26.82.73
    port: 22
    username: root
    password: js8zq596.A
    path: /var/cache/drone
    rebuild: true
    ignore_branch: true
    mount:
      - node_modules

trigger:
  branch:
    - master
