kind: pipeline
type: docker
name: install

steps:
#  - name: restore_cache
#    image: appleboy/drone-sftp-cache
#    settings:
#      server: 47.100.208.153
#      port: 22
#      username: root
#      password: js8zq596.A
#      path: /var/cache/drone
#      restore: true
#      ignore_branch: true
#      mount:
#        - node_modules

  - name: install
    image: js8zq332/node-yarn:latest
    environment:
      USERNAME:
        from_secret: username
      PASSWORD:
        from_secret: password
    commands:
      - echo ${DRONE_BRANCH}
      - echo $${USERNAME}
      - echo $${PASSWORD}
      - yarn install
      - yarn run build



#  - name: rebuild_cache
#    image: appleboy/drone-sftp-cache
#    settings:
#      server: 47.100.208.153
#      port: 22
#      username: root
#      password: js8zq596.A
#      path: /var/cache/drone
#      rebuild: true
#      ignore_branch: true
#      mount:
#        - node_modules
#  - rebuild_cache:
#    image: appleboy/drone-sftp-cache
#    server: 120.26.82.73
#    port: 22
#    username: root
#    password: js8zq596.A
#    path: /var/cache/drone
#    rebuild: true
#    ignore_branch: true
#    mount:
#      - node_modules

trigger:
  branch:
    - master

---
kind: secret
name: username
get:
  path: secret/data/docker
  name: username

---
kind: secret
name: password
get:
  path: docker
  name: password
#
#---
#kind: secret
#name: username
#get:
#  path: secrets/secrec/docker
#  name: username
